### ISSUE TITLE
::create_table in dog_spec.rb doesn't clear table

### ISSUE THREAD

**Issue by wwboyer** [learn-co-curriculum/bringing-it-all-together#31]
The README describes the test for ::create_table as:

```Ruby
    describe '::create_table' do
      it 'creates a dogs table' do
        DB[:conn].execute('DROP TABLE IF EXISTS dogs')
        Dog.create_table
     
        table_check_sql = "SELECT tbl_name FROM sqlite_master WHERE type='table' AND tbl_name='dogs';"
        expect(DB[:conn].execute(table_check_sql)[0]).to eq(['dogs'])
      end
    end
```

However, the actual `dog_spec.rb` file is missing the `DB[:conn].execute('DROP TABLE IF EXISTS dogs')` line. Earlier in the spec, however, the following code is present:

```Ruby
before(:each) do
    DB[:conn].execute("DROP TABLE IF EXISTS dogs")
    sql =  <<-SQL
      CREATE TABLE IF NOT EXISTS dogs (
        id INTEGER PRIMARY KEY,
        name TEXT,
        breed TEXT
        )
    SQL
    DB[:conn].execute(sql)
  end
```

So, in order to prevent the test from throwing a "table dogs already exists" error, the lab should be updated to either

- Tell the user that the table may already exist and account for that possibility in their code, and update the code snippet displayed in the lab to reflect this.
- Update the spec to contain the `DB[:conn].execute('DROP TABLE IF EXISTS dogs')` line.

or

- I can't read properly and need to update my prescription for my glasses.

Thanks!
Trey Boyer

**Comment by zoebisch** [comment]
I believe in the latter case, this causes the following issue:

def self.create_table

end

Or in other words, an empty create_table method will PASS.

to allow the same test to pass because the table gets created if it does not exist? At least that is what I believe I am seeing. So you create the table and then an empty method doesn't matter then.

Thanks - BZ

**Comment by curiositypaths** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#34.  We will add this to our internal work queue and
notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team
