### ISSUE TITLE
There are a couple of issues with the tests.

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/bringing-it-all-together#38]
Hello. I found a couple of VERY minor issues with the tests, but I wanted to bring them to your attention. First, the first test for Dog.find_or_create_by looks like this:

      it 'creates an instance of a dog if it does not already exist' do
            dog1 = Dog.create(name: 'teddy', breed: 'cockapoo')
            dog2 = Dog.find_or_create_by(name: 'teddy', breed: 'cockapoo')

            expect(dog1.id).to eq(dog2.id)
      end

However, despite the description, that test only checks that Dog.find_or_create_by_name doesn't create a duplicate dog. To check that it creates an instance of a dog if it does not already exist, you would have to do something like:

      dog1 = Dog.create(name: 'teddy', breed: 'cockapoo')
      dog2 = Dog.find_or_create_by(name: 'fido', breed: 'yellow lab')

      expect(dog2.id).to eq(2)

I don't know if it would be better to combine these into one test, or to have them separate.

The other issue that I found is that if I have the id attribute in the attr_accessor or attr_reader, but I don't specify the id in the #initialize method, the second attributes test still passes (although, to be fair, the third attributes test still fails as it should). I have attached a screenshot for clarification:

![orms lab screenshot](https://user-images.githubusercontent.com/38870640/49681943-0820bb00-fa5f-11e8-9cf9-82b8f2852239.gif)

Thanks for looking into this!
Sdcrouse

**Comment by sgharms** [comment]
@Sdcrouse Fixed!
