### ISSUE TITLE
update test doesn't call update

### ISSUE THREAD

**Issue by c1505** [learn-co-curriculum/bringing-it-all-together#4]
The update test doesn't call the update method and the tests pass prior to implementing it.  

The test is here

describe '#update' do
    it 'updates the record associated with a given instance' do
      teddy.save
      teddy.name = "Teddy Jr."
      teddy.save

```
  teddy_jr = Dog.find_by_name("Teddy Jr.")
  expect(teddy_jr.id).to eq(teddy.id)
end
```

**Comment by AnnJohn** [comment]
Hi, thanks for raising this issue. we'll look into this as soon as we can.
